# This is a basic workflow to help you get started with Actions

name: Create Container Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: test action
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test:ci
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          zeeko/adoc-editor-web
        tags: |
          type=ref,event=branch
          type=ref,event=pr
    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1.10.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERUSER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERPASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
