# This is a basic workflow to help you get started with Actions

name: Create Container Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: test action
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test:ci
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DockerUser }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DockerPassword }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.DockerRegistry }}
        # Docker repository to tag the image with
        repository: zeeko/adoc-editor-web
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
        # Always attempt to pull a newer version of the image
        always_pull: true
